### ISSUE TITLE
enhance our guidelines for safe and secure Ada SPARK to reference CWE

### ISSUE THREAD

**Issue by brobecke** [AdaCore/learn#1046]
Currently, the document refers to the ISO 24772 framework. This issue is an enhancement request to evaluate the merits of referencing the CWE codes, which are perceived to be more frequently used than ISO 24772. And if it makes sense, then this issue is to track the work needed to add those CWE codes.

Assuming we agree to use CWE, the other question is whether it would make sense to keep both? Or just have CWE codes replace the ISO 24772 ones.

**Comment by gusthoff** [comment]
> document refers to the ISO 24772 framework.

"document" => [Guidelines for Safe and Secure Ada/SPARK](https://github.com/AdaCore/learn/tree/master/content/courses/Guidelines_for_Safe_and_Secure_Ada_SPARK)

**Comment by frank-at-adacore** [comment]
Planning on adding a new subsection (mirroring the ISO 24772 subsection) listing the CWEs

Branch https://github.com/AdaCore/learn/tree/add_cwe_to_coding_standards
Pull Request https://github.com/AdaCore/learn/pull/1076

**Comment by dm-at-ada** [comment]
Changes have been merged into the main website branch and deployed (via #1076 and #1081), so marking this item as "closed" and will send an update to the owner of the original enhancement request.
