### ISSUE TITLE
Enhance "More about types" section

### ISSUE THREAD

**Issue by AdaDoom3** [AdaCore/learn#108]
The section "more about types" has a great organization for instructional purposes - hiding advanced information until the user is ready - but as a reference it might be confusing. For example, if one needs to look-up advanced topics about records they would not see them in the regular "records" category and would have to dig around.

Perhaps a solution might be just to remove the "More about types" category and make all of its subcategories unnested and at the forefront, or hide all topics related to types into an overarching category.

**Comment by gusthoff** [comment]
Thanks for the hint! A workaround (implemented in #744) is to move some sections to separate chapters and add cross-references.
