### ISSUE TITLE
Page adjusting its content on refresh

### ISSUE THREAD

**Issue by corentingay** [AdaCore/learn#109]
When refreshing or loading the page, it gives the impression that the page is adjusting its content before settling down for the final look.

Browser : Firefox

For example, on https://learn.adacore.com/courses/intro-to-ada/chapters/imperative_language.html
when I load the page, the code sample is not there and take a noticable time to display, same for the collapsed menu on the left.

**Comment by Robert-Tice** [comment]
Some javascript does some work on load to render the editors (and on the home page to render some content). This is unavoidable at the moment unfortunately.
