### ISSUE TITLE
Toggling "Settings->Use Tabbed Editor View" is too easy, and reverts your changes with no warning

### ISSUE THREAD

**Issue by brgaeke** [AdaCore/learn#1100]
I witnessed the following when working with a student: if you click the "Use Tabbed Editor View" checkbox or "Use the dark theme" checkbox in the "Settings" popup menu, your current changes are reverted from the text area. You are not warned before this happens, like you are when you hit the "Reset" button.

This is tied up with a closely related issue: it is too easy to _accidentally_ click "Use Tabbed Editor View" when you are aiming for the "Run" or "Compile" button below the edit widget!  This particularly shows up if you have your mouse over the edit widget, and then move down and to the left towards the "Run" or "Compile" button.  The "Run" or "Compile" button is ordinarily flush left, aligned with the left side of the edit widget, and just below it, so that your mouse naturally passes over the Settings popup area, activating it as you move it toward the "Run" or "Compile" button.  The resulting popup menu mostly obscures the "Run" or "Compile" button.

If you are a student who has typed something complicated in to try to solve a lab, and you go to hit Run, but miss the button, and as a result the editor throws away all your hard work, then you will be discouraged.

One possible way to fix this would be to make it so that Settings and Switches do not automatically open their respective menus just because you mouse over them (maybe you make it so that you have to click or click-and-hold to open the menu).  Another way might be to move them, e.g., so that they are right-justified rather than left-justified.  And certainly, if changes will be lost, a warning dialog should appear, allowing you to cancel the change and save your work.

**Comment by brgaeke** [comment]
![image](https://github.com/user-attachments/assets/a6f0f9af-2dd5-4b19-93aa-e86abfc17c07)

Red arrow shows sample direction of mouse track

**Comment by gusthoff** [comment]
Hey @brgaeke, 

Yes, I agree: losing all the work is indeed discouraging. We will work on improving this.

Thanks for reporting the issue and for all the suggestions!

**Comment by gusthoff** [comment]
* Menu with settings / switches was moved to the top:

![Screenshot 2024-09-08 at 16-12-37 Imperative language — learn-sandbox adacore com](https://github.com/user-attachments/assets/8166f06f-a64f-4b9c-9312-3aee41e6e0f3)

* Modal window asks for confirmation before reloading the page:

![learn_modal_window](https://github.com/user-attachments/assets/dacfbcf6-740c-49e3-8b92-17bdbd506256)

**Comment by gusthoff** [comment]
**Note**: these changes will be deployed by the end of September.
