### ISSUE TITLE
States #4: "N" is undefined

### ISSUE THREAD

**Issue by brgaeke** [AdaCore/learn#1102]
I witnessed the following with a student:
in https://learn.adacore.com/labs/intro-to-ada/chapters/subprograms.html#states-4
there is a confusing statement:

> - Procedure Set_Next updates the machine's state with the next one in a circular manner:
>    - In most cases, the next state of N is simply the next number (N + 1).

Nowhere else in the "States" labs is "N" mentioned, which was confusing to the student.

This could be fixed by:
1. referring to "State" which is the name of the variable that seems to be used elsewhere.

**Comment by gusthoff** [comment]
Hello @brgaeke, 

The explanation in that exercise is very confusing. We will certainly improve it and make it clear. Thanks for reporting the problem!
