### ISSUE TITLE
Lab test case result view UI improvement

### ISSUE THREAD

**Issue by brgaeke** [AdaCore/learn#1103]
I witnessed the following with a student:

![image](https://github.com/user-attachments/assets/abce93b9-ccf8-4fe0-8933-c964b70f5cd2)

The red arrows point to clickable areas that expand when clicked on, explaining to the student what went wrong (if anything) in each test case.
It seems that some people do not realize that the + is a thing they can click on.

The situation is better than in issue 1101, since there is a mouseover visual effect.
But it could be that replacing + with "click to see details +" and - with "click to hide -" or something would be more obvious.

Also, the text `Lab failed.` could be changed to say something like `Lab failed. Click test cases below to see details.`

**Comment by gusthoff** [comment]
I agree: despite the mouseover effect, it's not obvious that clicking on specific test cases will display more information. We will come up with improvements to the UI that make this behavior clear.

Thanks for reporting the issue and for the suggestions!

**Comment by gusthoff** [comment]
We're now using a more visible sign (triangle) with a more prominent color for the accordion element:

![Screenshot_2024-09-28_20-02-04](https://github.com/user-attachments/assets/45cac529-1d6d-49d4-b9b2-3b3d1fe7c36a)

**Comment by gusthoff** [comment]
The error message has been updated:

![Screenshot 2024-09-28_20-31-22](https://github.com/user-attachments/assets/9de23c56-342b-4d8d-a1d2-3dfcb48db348)

**Comment by gusthoff** [comment]
**Note**: these changes will be deployed to the learn website at the end of October.
