### ISSUE TITLE
Incorrect gnatprove arguments in 'Introduction to Spark'

### ISSUE THREAD

**Issue by ahahfilip** [AdaCore/learn#1148]
Hi! Thank you for your work.
I noticed that there's an error in the 'Introduction to Spark' section and probably in the following sections that use the same command:
`gnatprove -P main.gpr --level=0 --checks-as-errors --no-axiom-guard --mode=flow`
The following error is printed:
```
error: wrong argument "--no-axiom-guard" for --checks-as-errors, must be one of (on, off)
Try "gnatprove --help" for more information.
exit status: 1
```

**Comment by rowan-walshe** [comment]
Hi @ahahfilip. Thank you for reporting this issue. While doing some cleanup, I think I deployed the wrong version of the backend 🤦‍♂️

The issue should now be fixed, though let us know if you run into any other issues
