### ISSUE TITLE
How-to use Ada on embedded platforms

### ISSUE THREAD

**Issue by Jamen1993** [AdaCore/learn#119]
I'm really interested in using Ada on embedded platforms and I think that a section about using Ada on embedded platforms would add much value to the learning platform.

I'm highly interested in the following topics:

* Ada runtimes (ZFP ... Full)
* Porting the support package to new processors
* Ravenscar profile
* Dynamic memory allocation on embedded targets (e.g. custom allocators or allocation methods for memory pools)
* Writing HAL libraries (svd2ada tool)
* Interrupt handlers
* Sporadic tasks

I'm also very interested in the advanced Ada course that is already in progress. Keep up the good work!

**Comment by Fabien-Chouteau** [comment]
Hi @Jamen1993,

Thanks for you feedback.

We do plan to have an embedded Ada course on learn.adacore.com, we don't have a release date for the moment.

In the meantime, you can start with the examples of the `Ada Drivers Library` project. For instance using a `micro:bit` board: https://github.com/AdaCore/Ada_Drivers_Library/tree/master/examples/MicroBit

Best regards,
