### ISSUE TITLE
Wrong ASCII code

### ISSUE THREAD

**Issue by vdflorio** [AdaCore/learn#141]
Hello,
in the last script at https://learn.adacore.com/courses/intro-to-ada/chapters/more_about_types.html, line 21,  you mention "Assign the character at position 64 in the enumeration (which is 'A'). You should use 65 instead. Code 64 corresponds to character "@".
Kind regards

**Comment by gusthoff** [comment]
Very attentive of you. Thanks for reporting!

**Comment by vdflorio** [comment]
It’s been my pleasure, thank you very much!
Kind regards,
Vincenzo
