### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by vdflorio** [AdaCore/learn#150]
Hallo,

I collected a number of typos for you ;)

- In the Tasking section, paragraph on synchronization / rendez-vous, “[A task proceeds until it reaches an accept statement and then waits for the master task to synchronize with the it](https://learn.adacore.com/courses/intro-to-ada/chapters/tasking.html#synchronization-rendez-vous)”. (s/the it/it/).
- In the Tasking section, procedure `Show_Cycling_Task`, “[-- cycle of one seconds](https://learn.adacore.com/courses/intro-to-ada/chapters/tasking.html#cycling-tasks)”. (s/seconds/second/).
- In “Design by Contracts”, [first paragraph](https://learn.adacore.com/courses/intro-to-ada/chapters/contracts.html): “Parameter modes of a subprogram can be viewed as a simple of form of contracts” (s/a simple of/a simple/); and “these specification improve the consistency of the application” (s/specification/specifications/).
- The [second example in Design by Contracts](https://learn.adacore.com/courses/intro-to-ada/chapters/contracts.html#pre-and-postconditions) defines a Double function as follows:

        Function Double (A : Int_8) return Int_8 is
        (A * A)      -- etc

I cannot understand why this function is called `Double`. Could please call it `Square` or, if that identifier is already taken, perhaps something like `Square_Int_8`?
- Typo in OOP section, paragraph about tagget types : “[style similar to the one described at the beginning of this chaper](https://learn.adacore.com/courses/intro-to-ada/chapters/object_oriented_programming.html#tagged-types)” (s/chaper/chapter).
- Typo in section about the standard library, paragraph about instantiation : “[Containers are based on generic packagess](https://learn.adacore.com/courses/intro-to-ada/chapters/standard_library.html#instantiation)” (s/packagess/packages).
- Typo in section about the standard library, paragraph about accessing first and last elements: “[You can swap elements by calling the procedure Swap and retrieve a reference](https://learn.adacore.com/courses/intro-to-ada/chapters/standard_library.html#accessing-first-and-last-elements)]” (s/retrieve/retrieving/).

Kind regards,
Vincenzo

**Comment by Robert-Tice** [comment]
Hi Vincenzo,

Thanks for making us aware of these errors. We very much appreciate it! If you come across any more please let us know.

Thanks,
Rob

**Comment by Eidonko** [comment]
Hello Robert,
thank you very much for your kind message! Yes sure, if I would have any further remarks it will be a pleasure for me to inform you about them :)
All the very best,
Vincenzo
