### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by vdflorio** [AdaCore/learn#151]
Hello,

in the example at https://learn.adacore.com/courses/intro-to-ada/chapters/standard_library.html#operations-on-elements and following sections, you introduce packages such as

      package Integer_Sets is new Ada.Containers.Ordered_Sets
          (Element_Type => Integer);

and then you `use` those packages, as in

      use Integer_Sets;

This allows objects to be defined as simply as in

      S : Set;

When I first read this example, I was a little puzzled and asked myself, “where does this `Set` come from, and how is it related to `Integer_Sets`?” Obviously this is because the `use` statement allows for a more concise definition of set objects. The above statement actually means

      S : Integer_Sets.Set ;

I would suggest to use the above statement instead of the more concise one, as it tells more explicitly the relation between `S` and its package `Integer_Sets`. Or you could add a comment explaining that fact:

      S : Set ; -- more explicitly, this is   S : Integer_Sets.Set ;

The same suggestion applies to all the following examples; e.g., in Hashed Maps I would define M as

       M : Integer_Hashed_Maps.Map;

or add a comment.

Thank you,

best regards,
V.

**Comment by Robert-Tice** [comment]
Hi Vincenzo,

Thanks for your feedback. We have made some changes based on your suggestions. Let us know if the added comments make things a little clearer.

Thanks,
Rob

**Comment by Eidonko** [comment]
Hello Robert,

so kind of you to take my suggestions into account -- thank you very much!

Kind regards,
Vincenzo
