### ISSUE TITLE
HTML titles

### ISSUE THREAD

**Issue by pmderodat** [AdaCore/learn#157]
Hello,

Currently, all HTML pages have the same title: “learn.adacore.com”, making it hard to know which page is where when you have several tabs. I think it would be more useful if it was instead derived from the page’s top-level section.

For instance:

> Strongly typed language – Introduction to Ada – learn.adacore.com

for https://learn.adacore.com/courses/intro-to-ada/chapters/strongly_typed_language.html

> SPARK Overview – Introduction to SPARK – learn.adacore.com

for https://learn.adacore.com/courses/intro-to-spark/book/01_Overview.html

I think this pattern (specific title first and then name of the website) is quite common and the most helpful: see for instance titles for pages in GitHub.

**Comment by Robert-Tice** [comment]
We can definitely do "Page Title - learn.adacore.com". I'm not sure if we can add the parent document title in the middle.

**Comment by Robert-Tice** [comment]
I spoke too soon. #158
