### ISSUE TITLE
Intro to Ada: Strongly types language: Floating Point Types: Mantissa

### ISSUE THREAD

**Issue by Coder206** [AdaCore/learn#210]
Hello,

I am learning Ada by following [this wonderful tutorial](https://learn.adacore.com/courses/intro-to-ada/index.html), thank you! 

When I came to the [section Basic Properties of Floating Point Types](https://learn.adacore.com/courses/intro-to-ada/chapters/strongly_typed_language.html#basic-properties) in `Strongly types language`, it refers to the precision (the number of decimal of places in a floating point number) as a `mantissa`. Although this is accepted, it is less [ambiguous](https://en.wikipedia.org/wiki/Mantissa) to refer to it by the term `significand`. Would this be possible to change?

What are your thoughts on the matter?

Cheers,
@Coder206

**Comment by gusthoff** [comment]
Hello @Coder206,

Thanks for your interest in learning Ada!

Even though the term "mantissa" may sound ambiguous at first, it's actually standard terminology when referring to floating-point data types. The term you're suggesting ("significand") is actually uncommon in this context. Therefore, I prefer not to change the text.
