### ISSUE TITLE
Sharing this article about a beginner's first impressions of the learn platform

### ISSUE THREAD

**Issue by trosel** [AdaCore/learn#213]
https://words.steveklabnik.com/learning-ada

https://news.ycombinator.com/item?id=19510074

@steveklabnik

**Comment by steveklabnik** [comment]
Oh hey! I had been meaning to maybe file some issues... if it's useful, I'm happy to maybe make some concrete suggestions here.

**Comment by raph-amiard** [comment]
@steveklabnik you'd be more than welcome ! We're already going over your article and incorporating some changes based on your impressions/feedback. Don't hesitate to open specific issues :)

**Comment by steveklabnik** [comment]
For the record, I'm sad I never did this. Glad to see the stuff going on in the Ada world from afar, though :)
