### ISSUE TITLE
Code window is too small

### ISSUE THREAD

**Issue by raph-amiard** [AdaCore/learn#223]
For example in this lab:

https://learn-staging.adacore.com/labs/intro-to-ada/chapters/imperative_language.html

The editor in which the user is going to code the original solution is very small, and doesn't resize when you code in it. The user experience is very sub-optimal.

Not exactly sure what is the best way to fix this, but I imagine if the editor auto-resized when you add code that would be a good start ?

**Comment by Robert-Tice** [comment]
See proposed fix in #227

**Comment by Robert-Tice** [comment]
PR #227 approved and merged.
