### ISSUE TITLE
Useless Run button in labs

### ISSUE THREAD

**Issue by raph-amiard** [AdaCore/learn#224]
The Run button is pretty useless in labs, and confusing. Shouldn't we just remove it ?

See example in first intro-to-ada lab:

![strange](https://user-images.githubusercontent.com/478727/58319230-ca9bc880-7e19-11e9-8b88-2ce88f717f52.png)

**Comment by gusthoff** [comment]
Instead of removing the _Run_ button, we could associate it with a list of suggested arguments (the ones from the test cases).

**Comment by Robert-Tice** [comment]
The run button is necessary to test your code against a custom input. Maybe we can show/hide the run button with the Custom Input checkbox?

**Comment by raph-amiard** [comment]
Why not have only one button for run and submit, where the behavior changes depending on whether the box is checked or not ?

**Comment by Robert-Tice** [comment]
Fixed in PR #336
