### ISSUE TITLE
Variant of Examine button with explicit results for SPARK course

### ISSUE THREAD

**Issue by yannickmoy** [AdaCore/learn#236]
Right now we have a prove_flow_button that calls GNATprove in flow mode. When the checks all pass, this generates no messages. It would be better to use the new capability of flow analysis to list dependencies that it checked with --report=all. 

I suggest we add a parameter prove_flow_report_all_button that would add --report=all to flow mode.

When done, I can do a pass over SPARK course to adjust the source when useful.

**Comment by Robert-Tice** [comment]
This is now implemented on the server side with AdaCore/code_examples_server#19 and learn branch issues/236.

@yannickmoy I would recommend adding your changes to the SPARK courses that require the new report all examine button on the issues/236 branch. We can then do a PR and coordinate the merge into master with the PR for the server side.
