### ISSUE TITLE
Add Compile button to replace class ada-syntax-only 

### ISSUE THREAD

**Issue by yannickmoy** [AdaCore/learn#254]
As documented in CONTRIBUTING.md, class "ada-syntax-only" should still allow a compilation "Run" button to be displayed. That's not the case for the Swap example just before "Ensuring Control Structures Are Not Abused" in the SPARK-for-MISRA-C course:

https://learn.adacore.com/courses/SPARK_for_the_MISRA_C_Developer/chapters/03_syntactic_guarantees.html#ensuring-control-structures-are-not-abused

The default config should allow a Run button here:

:code-config:`run_button=True;prove_button=False;accumulate_code=False`

So why is there no button at all on this snippet?

**Comment by yannickmoy** [comment]
there are other snippets with the same problem in that chapter. The last snippet of the page is worse, as there should be a Prove button, but apparently ada-syntax-only prevents it altogether.

**Comment by Robert-Tice** [comment]
Enhancement completed in PR #334
