### ISSUE TITLE
possible runtime error in solution for Number labs

### ISSUE THREAD

**Issue by yannickmoy** [AdaCore/learn#256]
The solution of the Numbers lab has a problematic runtime error, pointed out by the Prove button:
display_numbers.adb:23:10: medium: overflow check might fail

Indeed, if X is Integer'First, abs X is raising a runtime error. The solution is to have a special case for Integer'First

Note that some other messages issued when hitting Prove are fine. Like the possible precondition failure with Integer'Value on the input.

**Comment by gusthoff** [comment]
This particular exercise was actually complicated for the first chapter of a beginner's course. Therefore, I decided to simplify it and solve the issue at the same time.
