### ISSUE TITLE
learn.adacore.com/courses/intro-to-spark/chapters/01_Overview.html#what-is-ittrivial example does not work 

### ISSUE THREAD

**Issue by mpazda** [AdaCore/learn#265]
https://learn.adacore.com/courses/intro-to-spark/chapters/01_Overview.html#what-is-it

"A trivial example" doesnt work

I had to do quite a bit of work to the example to get it to work

attached a zip spark.zip giving the failing code and a working example.

The subsequent examples may provide the information to get the trivial example to work.. but the trivial example should "just work"

It would also be helpful to be able to download the examples, or have them included in the GNAT share\examples\spark folder

**Comment by mpazda** [comment]
[spark.zip](https://github.com/AdaCore/learn/files/3535138/spark.zip)

**Comment by yannickmoy** [comment]
Hi mpazda,

In fact the only thing you need to do is apply SPARK_Mode globally on the files by defining a project file and inside it point to a configuration pragma file with "pragma SPARK_Mode" in it. That's what we document at the start of the SPARK User's Guide here: http://docs.adacore.com/spark2014-docs/html/ug/en/spark_mode.html#project-file-setup

If you want to extract automatically the code from the ReST pages for the learn website, you can do that by cloning the "AdaCore/learn" project, and use our own testing infrastructure to get the code snippets: https://github.com/AdaCore/learn/blob/master/engine/tests/compile_blocks.py

Then, everything we do on the server side to run GNAT/GNATprove is available on this other project: https://github.com/AdaCore/code_examples_server

We don't plan to add a "download" button to extract the sources and replay then locally, as the main objective of the learn website is precisely to be able to do this without installing GNAT or GNATprove. If you do, you may want to experiment with the examples provided in SPARK, and follow these other tutorials: http://docs.adacore.com/spark2014-docs/html/ug/en/source/gnatprove_by_example.html
