### ISSUE TITLE
 Interactive tutorials seem to not work

### ISSUE THREAD

**Issue by BottCode** [AdaCore/learn#272]
All interactive tutorials on https://learn.adacore.com/ seem broken. I've tried them on Google Chrome (Version 72.0.3626.121) and Firefox Quantum (67.0.2) on Manjaro Linux.

![image](https://user-images.githubusercontent.com/16674092/65030558-082fde80-d940-11e9-8bc9-3c82822a78ed.png)

**Comment by yannickmoy** [comment]
thanks @BottCode for the report, I confirm the server is down. will restart asap

**Comment by setton** [comment]
This is fixed, thank you for reporting this!
