### ISSUE TITLE
Incorrect Java example

### ISSUE THREAD

**Issue by tromey** [AdaCore/learn#273]
The Java example in https://github.com/AdaCore/learn/blob/master/courses/Ada_For_The_CPP_Java_Developer/chapters/06_Functions_and_Procedures.rst#general-form is not valid Java code, because in Java everything must be in a `class`.

One possible fix would be to move `Func` into `class ProcData`.  Perhaps it would make sense to make it `static` as well.

**Comment by setton** [comment]
@tromey thank you for the heads-up! Would you like to make a pull request? :-)

**Comment by tromey** [comment]
Thanks for fixing this.
