### ISSUE TITLE
Is GNATprove version on learn.adacore different from the one in GNAT Community edition?

### ISSUE THREAD

**Issue by BottCode** [AdaCore/learn#287]
Hi,

it seems to me that the GNATprove version on [learn.adacore](https://learn.adacore.com/courses/intro-to-spark/index.html) is different from the one included in GNAT Community edition package. 
Am I wrong? The one in GNAT community edition seems less powerful.

**Comment by setton** [comment]
Hello @BottCode - the version of gnatprove in production on learn.adacore.com is the one from GNAT Community 2019. If you find differences, it's probably something to do with the switched used for invocation... don't hesitate to ask if you would like more details.

**Comment by BottCode** [comment]
Got it, thanks for your answer.
