### ISSUE TITLE
Postcondition is correct but shouldn't be

### ISSUE THREAD

**Issue by raph-amiard** [AdaCore/learn#31]
In the SPARK course you have the following supposedly incorrect example showing how aliasing can happen

~~~sphinx
.. code:: ada run_button
    :class: ada-run-expect-failure

    procedure No_Aliasing is

       Total : Natural := 0;

       procedure Move_To_Total (Source : in out Natural)
         with Post => Total = Total'Old + Source'Old and Source = 0
       is
       begin
          Total  := Total + Source;
          Source := 0;
       end Move_To_Total;

       X : Natural := 3;

    begin
       Move_To_Total (X);     -- OK
       Move_To_Total (Total); -- Error
    end No_Aliasing;
~~~

It is marked as expect failure. However, after a bit of fiddling, it turns out that even with -gnata, the Post condition is respected even with unwanted aliasing. I'm not sure if that's the wanted effect, but either the example should be changed, either we should remove the expect-failure annotation

**Comment by yannickmoy** [comment]
agreed, and this is expected. I changed the example.
