### ISSUE TITLE
Auxiliary editable adb-s have no effect

### ISSUE THREAD

**Issue by Irvise** [AdaCore/learn#360]
Issue: editable .adb/s have no effect when compiling the main adb.

Example: in the [subprograms chapter](https://learn.adacore.com/courses/intro-to-ada/chapters/subprograms.html) the definition of increment_by.adb is editable and it is used in show_increment.adb. If increment_by.adb is edited (for example, add an extra + 2), the results of show_increment.adb are unchanged.

Expected result: modifications to files that are used to compile a program should affect the final output.

I think (as a student/reader) that if something is editable, it should have consequences if the code is being compiled, even if it is not the main adb. I know that this is not an easy task and one could just copy-paste de code into the file being compiled, but this is very tedious and unintuitive.

Could you add the ability for changes in auxiliary files to also take place in the final compilation? If it is not done, then, making the axulliary code modifiable may be confusing. Leaving it as highlighted text may be better.

Regards,

Fernando

**Comment by Robert-Tice** [comment]
Hi Fernando,

Thanks for reporting this issue. It is indeed a bug. Currently, aggregated files such as this aren't checked for changes before the code is submitted. Other editors, where all the code is in a single editor window (such as this: https://learn.adacore.com/courses/intro-to-ada/chapters/privacy.html#basic-encapsulation) will take into account changes in associated files. We will look into the issue and correct it shortly. 

Thanks again,
Rob

**Comment by Robert-Tice** [comment]
Fixed in PR #490
