### ISSUE TITLE
Set union and intersection operators are swapped in the introductory materials

### ISSUE THREAD

**Issue by timmyjose** [AdaCore/learn#365]
Lesson URL: https://learn.adacore.com/courses/intro-to-ada/chapters/standard_library_containers.html#operations-on-elements

Issue: The lesson mentions that `and` is used for `union` and `or` for `intersection`.

Correction: `and` is used for `intersection` and `or` for `union`.

**Comment by gusthoff** [comment]
Thanks for spotting this error (and for the fix as well)!
