### ISSUE TITLE
Suggestion to improve the `delay until` example in the chapter "Dates and Times' of the introductory course

### ISSUE THREAD

**Issue by timmyjose** [AdaCore/learn#367]
Chapter/Section URL:  https://learn.adacore.com/courses/intro-to-ada/chapters/standard_library_dates_times.html#delaying-using-date

Current : The given example has hardcoded values for the generated time to `delay until`.

Proposal: Generate the time to `delay until` by adding some number of seconds over the current time.

Example: Like the following modified example:

```
 -- display_delay_next_specific_time.adb

with Ada.Text_IO;
with Ada.Calendar;
with Ada.Calendar.Formatting;
with Ada.Calendar.Time_Zones;

procedure Display_Delay_Next_Specific_Time is
   Now                 : Ada.Calendar.Time := Ada.Calendar.Clock;
   Year_Number         : Ada.Calendar.Year_Number;
   Month_Number        : Ada.Calendar.Month_Number;
   Day_Number          : Ada.Calendar.Day_Number;
   Day_Duration_Number : Ada.Calendar.Day_Duration;

   TZ : Ada.Calendar.Time_Zones.Time_Offset :=
     Ada.Calendar.Time_Zones.UTC_Time_Offset;

   Next : Ada.Calendar.Time;
begin
   Ada.Calendar.Split
     (Now, Year_Number, Month_Number, Day_Number, Day_Duration_Number);

   declare
      Hour_Number, Minute_Number, Second_Number : Natural;
      Total_Seconds : Natural := Natural (Day_Duration_Number);
   begin
      Hour_Number   := Total_Seconds / 3_600;
      Total_Seconds := Total_Seconds rem 3_600;
      Minute_Number := Total_Seconds / 60;
      Total_Seconds := Total_Seconds rem 60;
      Second_Number := Total_Seconds;

      -- generate the time to delay until as current_time + 10 seconds (say)
      Next :=
        Ada.Calendar.Formatting.Time_Of
          (Year => Year_Number, Month => Month_Number, Day => Day_Number,
           Hour        => Hour_Number, Minute => Minute_Number,
           Second      => Second_Number + 10, Sub_Second => 0.0,
           Leap_Second => False, Time_Zone => TZ);

      Ada.Text_IO.Put_Line
        ("Current time is " & Ada.Calendar.Formatting.Image (Now, True, TZ));
      Ada.Text_IO.Put_Line
        ("Let's wait until " & Ada.Calendar.Formatting.Image (Next, True, TZ));

      delay until Next;

      Ada.Text_IO.Put_Line ("Enough waiting!");

      Now := Ada.Calendar.Clock;
      Ada.Text_IO.Put_Line
        ("Current time is " & Ada.Calendar.Formatting.Image (Now, True, TZ));
   end;
end Display_Delay_Next_Specific_Time;

```

Running it:

```
~/dev/study/ada/learn_adacore_com/introduction_to_ada/17_dates_and_times$ grun display_delay_next_specific_time.adb
gcc -c -g -gnata display_delay_next_specific_time.adb
gnatbind -x display_delay_next_specific_time.ali
gnatlink display_delay_next_specific_time.ali -g
Current time is 2020-05-26 19:06:32.61
Let's wait until 2020-05-26 19:06:43.00
Enough waiting!
Current time is 2020-05-26 19:06:43.00
```

**Comment by gusthoff** [comment]
Hello @timmyjose,

Thanks for your suggestion!

In general, hard-coded values should be avoided, so your approach is good. However, I'm afraid it might render that lesson too complicated. Since it's an introductory course, the goal there is to present the purpose of ```delay until```  in the simplest way possible. Adding the code you suggested would make it harder for some readers to understand what this is actually about.

That being said, this could be an interesting exercise for the labs. If you want, you could create an exercise — see https://github.com/AdaCore/learn/commit/753e209215119ab941ed2c6618ecaa5335160272 for an example. The only requirement is that the text output of the application must be constant, so that we could test against it.

What do you think?

**Comment by timmyjose** [comment]
Hey @gusthoff, thank you for the well-thought out comment! 

I fully agree with you - even as I created the issue, I knew that this example would probably be unnecessarily complicated for the basic course. 

I think the lab idea is most excellent! Let me take a look at the lab template that you've shared, and see if it might be a nicer fit over there. Thank you for the suggestion!
