### ISSUE TITLE
Mismatch in delay value in the "Dates and Times" chapter, section on benchmarking

### ISSUE THREAD

**Issue by timmyjose** [AdaCore/learn#368]
Section URL: https://learn.adacore.com/courses/intro-to-ada/chapters/standard_library_dates_times.html#benchmarking

Issue: The delay value in the program is 0.5s whereas in the description that follows, it's 5.0s. 

Proposal: Considering that this example is supposed to be a modification of the previous delay example (https://learn.adacore.com/courses/intro-to-ada/chapters/standard_library_dates_times.html#real-time), I propose that the program text be changed to reflect a delay of 5.0s to make the text and program consistent.

**Comment by gusthoff** [comment]
Thanks for the report and the changes!
