### ISSUE TITLE
Add SPARK configuration params to widgets

### ISSUE THREAD

**Issue by Robert-Tice** [AdaCore/learn#396]
Allow some SPARK configurations to be specified in the rst so that certain examples can take advantage of non-default gnatprove behavior.

**Comment by pat-rogers** [comment]
It would be good to control integer overflow, presumably via the -gnato?? switch. 
Probably a default of -gnat33 so it wouldn't be an issue until we wanted to talk about it, at which point we'd enable it selectively.
