### ISSUE TITLE
extra right parentheses in code example

### ISSUE THREAD

**Issue by moradiamr** [AdaCore/learn#408]
on the picture attached below I think the very last right parentheses which I have marked, is extra and needs to be removed.

<img width="805" alt="Screen Shot 2020-09-11 at 10 41 35 PM" src="https://user-images.githubusercontent.com/44950292/92971230-5e1a6200-f480-11ea-8f75-c44bb77b4638.png">

you can find this page in the link below.
https://learn.adacore.com/courses/Ada_For_The_CPP_Java_Developer/chapters/05_Type_System.html

**Comment by gusthoff** [comment]
Thanks for reporting!
