### ISSUE TITLE
Meters-to-miles conversion incorrect?

### ISSUE THREAD

**Issue by jstuyts** [AdaCore/learn#412]
If I am reading the code in [_Strongly type language_ » _Stong typing_](https://learn.adacore.com/courses/intro-to-ada/chapters/strongly_typed_language.html#strong-typing) correctly, the intention is to convert 100 meters to miles. But the outcome is 160.9 (1.60900E+02), which is definitely not correct.

Shouldn't the conversion be `Miles (Dist_Metric) / 1609.0`, resulting in 0.062 (6.21504E-02)?

**Comment by gusthoff** [comment]
Thanks for reporting! It was indeed incorrect. We've now fixed it.
