### ISSUE TITLE
Typo in content/courses/intro-to-ada/chapters/object_oriented_programming.rst

### ISSUE THREAD

**Issue by filip-gajowniczek-adacore** [AdaCore/learn#450]
The typo can be found by searching "substitability" and should read "substitutability".

**Comment by 96RadhikaJadhav** [comment]
@filip-gajowniczek-adacore  Could you please assign this issue to me? I wish to work on it.

**Comment by 96RadhikaJadhav** [comment]
@filip-gajowniczek-adacore I have created PRs for the issues #450 , #451, #452, #453. Could you please review all and let me know if any other changes required :) .
