### ISSUE TITLE
Grammatical error in content/courses/GNAT_Toolchain_Intro/chapters/gprbuild.rst

### ISSUE THREAD

**Issue by filip-gajowniczek-adacore** [AdaCore/learn#452]
The error can be found by searching: 
"The main file
doesn't necessary be called ``main.adb``;"

and should read:

"The main file
doesn't necessary need to be called ``main.adb``;"

**Comment by 96RadhikaJadhav** [comment]
@filip-gajowniczek-adacore  Could you please assign this issue to me? I wish to work on it.
