### ISSUE TITLE
Grammatical error in content/courses/GNAT_Toolchain_Intro/chapters/gnat_tools.rst

### ISSUE THREAD

**Issue by filip-gajowniczek-adacore** [AdaCore/learn#453]
The grammatical error can be found by searching:
"For
example, we may have multiple Ada packages contain in a single
file."

and should read:
"For
example, we may have multiple Ada packages contained in a single
file."

**Comment by 96RadhikaJadhav** [comment]
@filip-gajowniczek-adacore  Could you please assign this issue to me? I wish to work on it.
