### ISSUE TITLE
Content Request on content/courses/intro-to-ada/chapters/exceptions.rst

### ISSUE THREAD

**Issue by filip-gajowniczek-adacore** [AdaCore/learn#457]
This course lists the predefined Ada exceptions at the end.

Is the Assertion_Error exception missing from this list?

**Comment by pat-rogers** [comment]
Arguably no, it isn't missing, because it isn't defined in package Standard. Consider exceptions defined in the containers packages, for example. But it wouldn't hurt to have it, since it is a part of assertion semantics.

**Comment by gusthoff** [comment]
Thanks for the suggestion. The `Assertion_Error` exception is [now mentioned](https://github.com/AdaCore/learn/blob/c8b7b84990109bd287e44bdbc614d18973b506a4/content/courses/advanced-ada/chapters/exceptions.rst) in the (upcoming) Advanced Ada course. 

Of course, I could mention it in this course. For example:

```
In addition to these predefined exceptions, it's worth mentioning that we have
the :ada:`Assertion_Error` exception from the :ada:`Ada.Assertions` package.
This exception is raised when a call to an :ada:`Assert` fails.
```

This, however, would require a new section about asserts, which is too *advanced* for this course in my opinion. Therefore, I'll have to skip your suggestion.
