### ISSUE TITLE
Introduction to Ada: Arrays request for more detail on unconstrained arrays

### ISSUE THREAD

**Issue by filip-gajowniczek-adacore** [AdaCore/learn#494]
On page:https://learn.adacore.com/courses/intro-to-ada/chapters/arrays.html

There is a statement which reads
"
Although different instances of the same unconstrained array type can have different bounds, a specific instance has the same bounds throughout its lifetime. This allows Ada to implement unbounded arrays efficiently; instances can be stored on the stack and do not require heap allocation as in languages like Java.
"

The term "unbounded array" might be conflated with a vector/dynamic array https://www.google.com/search?client=firefox-b-1-d&q=unbounded+array

Recommend adding detail that an unconstrained array will have a fixed size upon instantiation that does not vary throughout its lifetime.

**Comment by gusthoff** [comment]
The term "unbounded array" was wrong in this context. Fixed with #595.
