### ISSUE TITLE
“The declaration of T as private indicates that you can map any type to it.” - this is incorrect

### ISSUE THREAD

**Issue by ButcherAdaCore** [AdaCore/learn#496]
With generic parameter declarations the following is said to indicate that you can map "any type" to it:
```
generic
   type T is private;
```
(ref: [https://learn.adacore.com/courses/intro-to-ada/chapters/generics.html])

However according to the compiler the actual for "T" must be a definite subtype.

For example instantiating T with a String would not compile.

In addition if you want to include Unconstrained Arrays in the definition of “any type” you’d need to declare:
```
generic
   type T (<>) is private; 
```

Therefore:
 "_The declaration of T as private indicates that you can map any type to it._”

should say:
 "_The declaration of T as private indicates that you can map any **definite** type to it._”

Plus it would be great to get a detailed breakdown of how the differing syntax used with Generic Parameter declarations affects what can be done with the generic. Including why you need to use the `(<>)` box notation to allow unconstrained arrays to be included in the definition of "all types" above.

**Comment by gusthoff** [comment]
Hi Paul, 

Thanks a lot for catching and reporting this issue. I've just uploaded a small PR for this: https://github.com/AdaCore/learn/pull/514

I'll leave the more elaborate discussion about generic `type T` vs `type T (<>)` for the upcoming _Advanced  Ada_ course.

**Comment by ButcherAdaCore** [comment]
Looks good to me! Thanks for sorting @gusthoff
