### ISSUE TITLE
Review Unchecked_Conversion for correctness in Ada for the C developer

### ISSUE THREAD

**Issue by filip-gajowniczek-adacore** [AdaCore/learn#504]
In this chapter of the book: https://learn.adacore.com/courses/Ada_For_The_Embedded_C_Developer/chapters/06_Translation.html#

the following statement is made:
"Also note that Unchecked_Conversion can only be instantiated for constrained types"

However, per the standard http://www.ada-auth.org/standards/12aarm/html/AA-13-9.html
"The size of the formal parameter S in an instance of Unchecked_Conversion is that of its subtype. [This is the actual subtype passed to Source, except when the actual is an unconstrained composite subtype, in which case the subtype is constrained by the bounds or discriminants of the value of the actual expression passed to S.]"

I have written a reproducer with Unchecked_Conversion instantiated for an unconstrained array which does compile:
```
begin
   declare
      type Payload is record
         I : Integer;
         F : Float;
      end record;

      function Process (Data : String) return Payload is
         subtype Input_String is String (Data'First .. Data'Last);
         function Convert is new Ada.Unchecked_Conversion (Source => Input_String, Target => Payload);
--           Heap_Data  : String := new String'(Data);
--           Return_Value : Payload with Address => Data'Address;
         Return_Value : Payload;
      begin
--           Put_Line ( Data'Size'Image );
--           Put_Line ( Convert (Data)'Size'Image);
--           return Convert (Data);
         Return_Value := Convert ( Data );
         Put_Line (Return_Value.F'Valid'Image);
         return Return_Value;
      end Process;
      P : Payload;
   begin
      P := Process ("CATS ARE AWESOME");
      Put_Line (P.I'Image);
      Put_Line (P.F'Image);
   end;
end Main;
```

**Comment by pat-rogers** [comment]
Input_String is constrained...

**Comment by filip-gajowniczek-adacore** [comment]
> 
> 
> Input_String is constrained...

You are absolutely correct. The reproducer I meant to post is:
```
   declare
      type Payload is record
         I : Integer;
         F : Float;
      end record;

      function Process (Data : String) return Payload is
         function Convert is new Ada.Unchecked_Conversion (Source => String, Target => Payload);
         Return_Value : Payload;
      begin
         Return_Value := Convert ( Data );
         Put_Line (Return_Value.F'Valid'Image);
         return Return_Value;
      end Process;
      P : Payload;
   begin
      P := Process ("CATS ARE AWESOME");
      Put_Line (P.I'Image);
      Put_Line (P.F'Image);
   end;
```

**Comment by pat-rogers** [comment]
The effect of a call to unchecked conversion is defined if all the requirements listed in 13.8(6..10) are true. One of those is not necessarily true for the above code:

   • S'Size = Target'Size 

where S is the name of the formal parameter of an instance, ie Convert. For an unconstrained composite subtype such as String, the subtype of S is constrained by the bounds of the value of the actual parameter passed to S, so Data's bounds.  Hence whether the effect is defined depends on the call to Convert.

The value for Target'Size depends on the sizes of Integer and Float in type Payload, and that depends on the machine. Typically it will be 64 bits but could be bigger as time goes by.

The call to Process passes 16 characters, so 128 bits, likely not the same size as Target, so probably the compiler just slices off the first 64 bits of the string and converts that. Who knows.

For the effect to be defined, make the input string to the U_C be the exact size of Payload, something like this:

   subtype Payload_String is String (1 .. Payload'Size / Character'Size);

   function Process (Data : Payload_String) return Payload is
      function As_Payload is new Ada.Unchecked_Conversion (Source => Payload_String, Target => Payload);
      Return_Value : Payload;
   begin
      Return_Value := As_Payload (Data);
      Put_Line (".F is valid: " & Return_Value.F'Valid'Image);
      return Return_Value;
   end Process;

On my machine Payload_String'Length is 8, so trim the actual for the call accordingly:

   P := Process ("CATS ARE");   --  AWESOME");

Make sense?

**Comment by pat-rogers** [comment]
> For example, an improvement in my opinion would be:
> "Also note that Unchecked_Conversion will only have defined behavior 
> when instantiated for constrained types"
> (this is probably oversimplified, but hopefully illustrates my point).


Right, I agree with that.
