### ISSUE TITLE
Logic error in case statement example

### ISSUE THREAD

**Issue by gcaplan** [AdaCore/learn#576]
The example here is passing strange:

https://learn.adacore.com/courses/intro-to-ada/chapters/imperative_language.html#imperative-language-case-statement

You have the cardinal point 0|360 assigned to due east. While 0|360 is universally assigned to due north.

All the other cardinal points are similarly out by 90 degrees.

Which only goes to show, even the most rigorous language can't protect you from logic bugs :-)

Excellent tutorial by the way - much appreciated. But with a language that's marketed to safety-conscious engineers it might be better if you didn't send them off in the wrong direction...

```    case N is
         when 0 | 360 =>
            Put_Line (" is due east");
         when 1 .. 89 =>
            Put_Line (" is in the northeast quadrant");
         when 90 =>
            Put_Line (" is due north");
         when 91 .. 179 =>
            Put_Line (" is in the northwest quadrant");
         when 180 =>
            Put_Line (" is due west");
         when 181 .. 269 =>
            Put_Line (" is in the southwest quadrant");
         when 270 =>
            Put_Line (" is due south");
         when 271 .. 359 =>
            Put_Line (" is in the southeast quadrant");
         when others =>
            Put_Line (" Au revoir");
            exit;
      end case;
```

**Comment by gusthoff** [comment]
Thanks for reporting the issue!

It was fixed with PR #580 and is now published on learn.adacore.com.
