### ISSUE TITLE
Feature request - option to set dark editor theme globally

### ISSUE THREAD

**Issue by gcaplan** [AdaCore/learn#577]
I'm finding that the dark theme for the code editor is far more legible than the default theme.

But so far as I can tell, I can only set it case-by-case.

My request is that there is an option to set this globally for all code panels, perhaps in the gear drop-down menu.

If this capability is there it's not very discoverable and I've missed it.

**Comment by gusthoff** [comment]
Support for dark mode was introduced a while ago (October, 2023) with this pull request: #948. (Dark mode is set automatically based on browser/system preferences — no drop-down menu option, though.)
