### ISSUE TITLE
.ads files not explained at the point they are introduced

### ISSUE THREAD

**Issue by gcaplan** [AdaCore/learn#578]
I hope you don't mind if I post my impressions as I go. As someone who has written docs, I'm probably more nit-picky than most. If my comments aren't useful, please let me know.

At the point you introduce .ads files, there's no explanation of what they are. For anyone who hasn't used Modula, their role and usage is not obvious. I had to google to put them into some context. 

https://learn.adacore.com/courses/intro-to-ada/chapters/subprograms.html

To the new user from languages like Python, C# & Java they might look like an irritation. A crisp explanation of their advantages to both the compiler and the developer might help cushion the blow.

**Comment by Pax2513** [comment]
I second this. The course is meant to be an _introduction_ to Ada, so explanations, even short ones, on fundamentals like what an ADS file is should not be skipped.
