### ISSUE TITLE
Exotic character in menu

### ISSUE THREAD

**Issue by pmderodat** [AdaCore/learn#60]
When you put the cursor on the title of the current section (left side menu), there seem to be an exotic character that is used. I thought I had a pretty complete set of fonts installed on my computer, so I guess a non negligible amount of people will also see this:

![unifont](https://user-images.githubusercontent.com/758452/42753395-14ab5248-88f1-11e8-9f49-588df90cec95.png)

Could we use something else instead?

**Comment by Robert-Tice** [comment]
This is fixed in pull request #57 FontAwesome was broken in the version we were using for glyphs. So that has been replaced.

**Comment by pmderodat** [comment]
Ok great, thanks!
