### ISSUE TITLE
Examples are incomplete when only reading the PDF versions

### ISSUE THREAD

**Issue by FryingPanBrock** [AdaCore/learn#626]
All of the examples in the courses have example files that can be downloaded. E.g. in the [Hello World example in Ada,](https://learn.adacore.com/courses/intro-to-ada/chapters/imperative_language.html) only the source code of greet.adb is shown. However, the example involves the use of the files main.gpr and main.adc. There is no way to know this just from reading the PDF file. Thus, I suggest either including the source code of the additional example files in the PDF just underneath the .adb source code, or making a ZIP archive containing the book along with all of the example files.

For example, for the course [Introduction to Ada,](https://learn.adacore.com/courses/intro-to-ada/index.html) you would create a ZIP archive containing the PDF and a subfolder for each of the examples where the subfolder contains the code files of the corresponding example. The subfolders could be prefixed with numbers to ensure that they are sorted in the correct order. For example:

introduction_to_ada.zip:
- introduction_to_ada.pdf
- Examples/
  - 01.Imperative_Language.Greet/
    - greet.adb
    - main.adc
    - main.gpr
  - 02.Imperative_Language.Greet_2/
    - greet.adb
    - main.adc
    - main.gpr
  - 03.Imperative_Language.Check_Positive/
    - check_positive.adb
    - main.adc
    - main.gpr
  - etc.

The same would be done for all of the other courses offered on [learn.adacore.com.](https://learn.adacore.com/index.html)

Aside: thank you very much for creating these resources! Not everyone has the money to spare for Barnes' book, especially if one is a student completing a course in Ada.

**Comment by gusthoff** [comment]
ZIP file containing all source-code examples is now available on the website.
