### ISSUE TITLE
Missing inline code blocks

### ISSUE THREAD

**Issue by Roldak** [AdaCore/learn#63]
I'm reporting all the pieces of code inside the text that should use an inline code format.

- [ ] https://learn-staging.adacore.com/courses/intro-to-ada/chapters/strongly_typed_language.html#derived-types : "Social_Security"
- [ ] https://learn-staging.adacore.com/courses/intro-to-ada/chapters/records.html#aggregates : "Ada_Birthday" and "Leap_Day_2020".

**Comment by Robert-Tice** [comment]
Similar issue here where text doesn't display in a code block:
https://learn-staging.adacore.com/courses/intro-to-ada/chapters/exceptions.html#exception-declaration

**Comment by raph-amiard** [comment]
Thanks @Roldak ! @Robert-Tice Can't reproduce, Fabien reported the same issue but I don't have it here, might be a glitch because of the failure of the cloudchecker last time.
