### ISSUE TITLE
Necessity to use Pragma Assert ?

### ISSUE THREAD

**Issue by Ilari1** [AdaCore/learn#649]
Hi all,

at https://learn.adacore.com/courses/SPARK_for_the_MISRA_C_Developer/chapters/04_strong_typing.html#arithmetic-operations-on-arithmetic-types
we find the following example concerning enum types with 2 examples on Boolean & a specific enum type.

with Ada.Text_IO; use Ada.Text_IO;

procedure Ok_Arith is

   B1 : constant Boolean := False;
   B2 : constant Boolean := Boolean'Succ (B1);
   B3 : constant Boolean := Boolean'Pred (B2);

   type Fruit is (Apple, Orange);
   F1 : constant Fruit := Apple;
   F2 : constant Fruit := Fruit'Succ (F1);
   F3 : constant Fruit := Fruit'Pred (F2);

begin
   pragma Assert (B1 = B3);
   pragma Assert (F1 = F3);

   for B in Boolean loop
      Put_Line (B'Img);
   end loop;

   for F in Fruit loop
      Put_Line (F'Img);
   end loop;
end Ok_Arith;

-The example shows us an example of using the 2 attributes Pred & Succ with a example of the ''Pragma Assert''.
If the pragma is not present, there is the following compilation warning :

> Compile
>    [Ada]          ok_arith.adb
> ok_arith.adb:10:03: warning: constant "B3" is not referenced
> ok_arith.adb:15:03: warning: constant "F3" is not referenced Bind
>    [gprbind]      ok_arith.bexch
>    [Ada]          ok_arith.ali
> Link
>    [link]         ok_arith.adb

-The necessity to "reference" B3 & F3 is not clear for me.
I've 2 issues in fact :
     -the first one is why we need to reference a constant ?
     -the second one is why Gnat considers differently B3 & B2 (respectively F3 & F2) ?

Is anybody from AdaCore could elaborate on the warning from the Gnat compiler, please?
BR

**Comment by Ilari1** [comment]
Ps : addendum, what's the text editor used on the site to show & modify source code?
It's interesting because it shows a vertical line between structures.

**Comment by gusthoff** [comment]
Hello @Ilari1, 

I'll try to answer your questions:

> -the first one is why we need to reference a constant ?

We don't really _need_ to reference it. The compiler is just giving you a warning in this case.

> -the second one is why Gnat considers differently B3 & B2 (respectively F3 & F2) ?

It's because, if you remove the lines with `pragma`, `B2` is still referenced in the declaration of `B3`, while `B3` isn't referenced anywhere.

> Ps : addendum, what's the text editor used on the site to show & modify source code?

It's a custom editor based on Ace. You can find the source-code here:

https://github.com/AdaCore/learn/tree/master/frontend/src/ts
