### ISSUE TITLE
Expand a row collapse the others

### ISSUE THREAD

**Issue by AdrienBoulanger** [AdaCore/learn#66]
In the side tree view, expanding a row collapse all the others, it would be useful to have the Introduction to Ada + Introduction to Spark expanded at the same time (for navigation purpose)

**Comment by Robert-Tice** [comment]
Currently sphinx is generating only the current view of the sidebar toctree. Children of siblings in the tree are not created until the sibling link is clicked and the children are in the immediate scope.

**Comment by Robert-Tice** [comment]
Closing this for now. Adding the ability to have the entire toctree expanded at once would create a UI issue. We would also have to override the theme js. We can reopen in the future if this feature gets more requests.
