### ISSUE TITLE
Code editors lacks several pixels at the bottom

### ISSUE THREAD

**Issue by pmderodat** [AdaCore/learn#67]
On Firefox 61.0.1 (Linux 64bit), the code editor lacks several pixels at the bottom so we can see underscores:

![underline](https://user-images.githubusercontent.com/758452/42764903-10e6d832-8917-11e8-8440-6f5fd3123543.png)

**Comment by Robert-Tice** [comment]
I'm guessing this should be fixed from the code_examples_server side.
