### ISSUE TITLE
Web VM image not available to the VirtualBox Vagrant provider

### ISSUE THREAD

**Issue by ronan-d** [AdaCore/learn#722]
Commit e281f6c79 pinned the web VM to an image that's only listed as available
for VMmare at https://app.vagrantup.com/bento/boxes/ubuntu-21.10.

Trying to run `vagrant up` with Vagrant and VirtualBox installed leads to an
error message:

```
$ vagrant up
Bringing machine 'web' up with 'virtualbox' provider...
Bringing machine 'epub' up with 'virtualbox' provider...
Bringing machine 'server' up with 'virtualbox' provider...
==> web: Box 'bento/ubuntu-21.10' could not be found. Attempting to find and install...
    web: Box Provider: virtualbox
    web: Box Version: 202112.23.0
==> web: Loading metadata for box 'bento/ubuntu-21.10'
    web: URL: https://vagrantcloud.com/bento/ubuntu-21.10
The box you're attempting to add has no available version that
matches the constraints you requested. Please double-check your
settings. Also verify that if you specified version constraints,
that the provider you wish to use is available for these constraints.

Box: bento/ubuntu-21.10
Address: https://vagrantcloud.com/bento/ubuntu-21.10
Constraints: 202112.23.0
Available versions: 202112.19.0, 202112.23.0
```

I'm not familiar with Vagrant. I think there are two options:

- Change the web VM image to one that's available to the VirtualBox provider.
- Change the instructions in `README.md` so that VirtualBox is replaced with
  VMware.

**Comment by gusthoff** [comment]
Thanks for reporting the issue!

Yes, you're absolutely right: it should have been pinned to `202112.19.0` instead. I'll fix it.

For the moment, you could simply remove the `box_version` entries from the Vagrant file. Sorry for the inconvenience!
