### ISSUE TITLE
MWAC-banner.png should be a https link

### ISSUE THREAD

**Issue by joeldiasmarques** [AdaCore/learn#74]
I've got a warning for the website certificate: the banner: http://blog.adacore.com/uploads/_1800xAUTO_crop_center-center/MWAC-banner.png should be a *HTTPS* link

**Comment by Robert-Tice** [comment]
Fixed in PR #77

**Comment by joeldiasmarques** [comment]
Note that in the HTML body, there is still some HTTP reference:
class="mwac-banner docutils container"

<img alt="http://blog.adacore.com/uploads/_1800xAUTO_crop_center-center/MWAC-banner.png" src="http://blog.adacore.com/uploads/_1800xAUTO_crop_center-center/MWAC-banner.png" style="width: 100pc;">
