### ISSUE TITLE
C++ bitwise operators misconstrued as boolean operators

### ISSUE THREAD

**Issue by fisherro** [AdaCore/learn#803]
In this section: https://learn.adacore.com/courses/Ada_For_The_CPP_Java_Developer/chapters/04_Statements_Declarations_and_Control_Structures.html#conditions

The text suggests that the C++ bitwise operators are boolean operators, which is confusing to a C++ programmer. Yes, the bitwise operators are not short-circuiting, but that is possibly the least important difference between them. One cannot be substituted for the other without careful consideration.

It would probably be best to remove the references to the C++ bitwise operators and just stick to the point that the Ada `and` and `or` are not short-circuiting the way the C++ boolean operators are.

**Comment by gusthoff** [comment]
Yes, we agree with you that C/C++ bitwise operators are more complicated than what the text is describing. However, we're focusing exclusively on the non-short-circuiting aspect while we mention the difference between short-circuiting and non-short-circuiting operators and compare the three languages.

If we remove the references to bitwise operators from the text, as you're suggesting, other readers might rightly point out that we're skipping a feature that does exist in Java and C/C++. Therefore, we'll keep the text as it is.

**Comment by fisherro** [comment]
They aren't more complicated. They do something entirely different.

The text says "It's more customary to use && and || in C++ and Java than & and | when writing boolean expressions." It's not customary. It's writing correct code instead of incorrect code. Using bitwise operators for a Boolean expression is simply wrong. It is saying something completely different.

Here's an example that demonstrates that: http://coliru.stacked-crooked.com/a/b20dc664c4d72b07

**Comment by gusthoff** [comment]
This was your code example:

```cpp
#include <iostream>

int main()
{
    int a = 2;
    int b = 4;
    std::cout << (a & b) << '\n';
    std::cout << (a && b) << '\n';
}
```

What this code shows is in an example of bit-masking. Here, the code is using an integer value as a bit-field and performing bit-wise operations. 

Although bit-masking is very common in C and C++ code, this is not what Boolean expressions are about. (Just as a reminder: the section of the book you mentioned is explicitly talking about "if-else" conditions...) If you want to write Boolean expressions, you have to use Boolean types — i.e. the C++ ``bool`` type.

> Using bitwise operators for a Boolean expression is simply wrong.

This statement is wrong: you *can* use bit-wise operators for Boolean expressions. I can demonstrate this with the following C++ code:

```cpp
#include <iostream>
#include <string>

bool
show_bool_a(bool a)
{
    std::cout << " [[a = " << a << "]] ";
    return a;
}

bool
show_bool_b(bool b)
{
    std::cout << " [[b = " << b << "]] ";
    return b;
}

void
show_bool_ops_ext(bool a, bool b)
{
    std::cout << "a &  b = " << (show_bool_a(a) &  show_bool_b(b)) << std::endl;
    std::cout << "a && b = " << (show_bool_a(a) && show_bool_b(b)) << std::endl;
    std::cout << "a |  b = " << (show_bool_a(a) |  show_bool_b(b)) << std::endl;
    std::cout << "a || b = " << (show_bool_a(a) || show_bool_b(b)) << std::endl;
    std::cout << std::endl;
}

void test_bool_op(bool test_result)
{
    if(test_result) {
        std::cout << "TEST PASSED!" << std::endl;
    }
    else {
        std::cout << "TEST FAILED!" << std::endl;
    }
}

void
show_bool_ops(bool a, bool b)
{
    std::cout << "a &  b = " << (a & b)  << std::endl;
    std::cout << "a && b = " << (a && b) << std::endl;
    test_bool_op((a & b) == (a && b));

    std::cout << "a |  b = " << (a | b)  << std::endl;
    std::cout << "a || b = " << (a || b) << std::endl;
    test_bool_op((a | b) == (a || b));

    std::cout << std::endl;
}

void
show_bool_ops_test(bool a, bool b)
{
    std::cout << "a = " << a << std::endl;
    std::cout << "b = " << b << std::endl;

    show_bool_ops(a, b);
    // show_bool_ops_ext(a, b);
}

int main()
{
    bool a, b;

    show_bool_ops_test(false, false);
    show_bool_ops_test(true, false);
    show_bool_ops_test(false, true);
    show_bool_ops_test(true, true);
}
```

This is the output of the application:

```
a = 0
b = 0
a &  b = 0
a && b = 0
TEST PASSED!
a |  b = 0
a || b = 0
TEST PASSED!

a = 1
b = 0
a &  b = 0
a && b = 0
TEST PASSED!
a |  b = 1
a || b = 1
TEST PASSED!

a = 0
b = 1
a &  b = 0
a && b = 0
TEST PASSED!
a |  b = 1
a || b = 1
TEST PASSED!

a = 1
b = 1
a &  b = 1
a && b = 1
TEST PASSED!
a |  b = 1
a || b = 1
TEST PASSED!
```

As the output shows, using bit-wise operators in Boolean expressions doesn't change the result. However, using short-circuiting in C/C++ is preferred for performance reasons: you can potentially save some CPU cycles here and there.

Also, if you call the ``show_bool_ops_ext`` function instead of the ``show_bool_ops`` function in the example, you can see the short-circuiting (and non-short-circuiting) in action: 

```
a = 0
b = 0
a &  b =  [[a = 0]]  [[b = 0]] 0
a && b =  [[a = 0]] 0
a |  b =  [[a = 0]]  [[b = 0]] 0
a || b =  [[a = 0]]  [[b = 0]] 0

a = 1
b = 0
a &  b =  [[a = 1]]  [[b = 0]] 0
a && b =  [[a = 1]]  [[b = 0]] 0
a |  b =  [[a = 1]]  [[b = 0]] 1
a || b =  [[a = 1]] 1

a = 0
b = 1
a &  b =  [[a = 0]]  [[b = 1]] 0
a && b =  [[a = 0]] 0
a |  b =  [[a = 0]]  [[b = 1]] 1
a || b =  [[a = 0]]  [[b = 1]] 1

a = 1
b = 1
a &  b =  [[a = 1]]  [[b = 1]] 1
a && b =  [[a = 1]]  [[b = 1]] 1
a |  b =  [[a = 1]]  [[b = 1]] 1
a || b =  [[a = 1]] 1
```
