### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by M4R5** [AdaCore/learn#81]
This issue and its comments should refer to typos.
Please add any typo you found using check-box, it will be easier to see what have been corrected.

- [ ] https://github.com/AdaCore/learn/blob/master/courses/intro-to-ada/advanced_ada.rst
  - [x] Procedures **ares** similar to functions in C or C++ that return void. We'll see later how to declare functions in Ada.
  - [x] Ada's if **statementis** pretty unsurprising in form and function:
  - [x] You can **have?** variables, constants, types, inner subprograms, and other entities there. For example:

**Comment by M4R5** [comment]
- [ ] https://github.com/AdaCore/learn/blob/master/courses/intro-to-ada/chapters/strongly_typed_language.rst
  - [ ] Ada does not mandate the range of the built-in type Integer. An implementation for a 16-bit target would likely choose the range −2^(15) through **2^(31−1)**

**Comment by raph-amiard** [comment]
Done, thank you Marc!
