### ISSUE TITLE
No syntax highligting on code block inside `In GNAT` box

### ISSUE THREAD

**Issue by Fabien-Chouteau** [AdaCore/learn#83]
Seen here:
https://learn-staging.adacore.com/courses/intro-to-ada/chapters/subprograms.html#function-calls

Source code is here:
https://github.com/AdaCore/learn/blame/master/courses/intro-to-ada/chapters/subprograms.rst#L225

**Comment by Fabien-Chouteau** [comment]
Another one but not in a `In GNAT` box. This one makes the next code blocks fail because a package is missing.

Seen here:
https://learn-staging.adacore.com/courses/intro-to-ada/chapters/exceptions.html#exception-declaration

Source code is here:
https://github.com/AdaCore/learn/blame/master/courses/intro-to-ada/chapters/exceptions.rst#L27

**Comment by raph-amiard** [comment]
Yo @Fabien-Chouteau can you test again ? Both work correctly for me on staging right now

**Comment by raph-amiard** [comment]
Reopen if needed :)

**Comment by Fabien-Chouteau** [comment]
:+1:
