### ISSUE TITLE
Running the Storage Check example does not show the expected exception (see the link below)

### ISSUE THREAD

**Issue by foroughgoudarzi** [AdaCore/learn#937]
https://learn.adacore.com/courses/advanced-ada/parts/control_flow/exceptions.html#storage-check

**Comment by gusthoff** [comment]
When I build and run the code example locally, I see the exception as expected:

```
Allocating RAV1...
Allocating RAV2...

raised STORAGE_ERROR : s-poosiz.adb:108 explicit raise
```

So the problem might be related to an issue in the backend.
