### ISSUE TITLE
Generate pdf versions of courses

### ISSUE THREAD

**Issue by Robert-Tice** [AdaCore/learn#98]

**Comment by Robert-Tice** [comment]
This will be dependent on the solution to #107. The compiler/prover outputs should be included with the code snippets.

**Comment by Earnestly** [comment]
I am currently working around this by commenting out the `widget_extension` item from the `extensions` list in https://github.com/AdaCore/learn/blob/master/engine/sphinx/conf.py#L49-L56

**Comment by Robert-Tice** [comment]
Done in PR #296
